runtime: nodejs12

handlers:
- url: /googledce38e530879d696\.html
  static_files: googledce38e530879d696.html
  upload: googledce38e530879d696\.html
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /favicon-32x32\.png
  static_files: favicon-32x32.png
  upload: favicon-32x32\.png
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /favicon-96x96\.png
  static_files: favicon-96x96.png
  upload: favicon-96x96\.png
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /favicon-16x16\.png
  static_files: favicon-16x16.png
  upload: favicon-16x16\.png
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /butterfly\.svg
  static_files: butterfly.svg
  upload: butterfly\.svg
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /.*
  static_files: index.html
  upload: index\.html
  expiration: "3d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: script-src 'self'
    Referrer-Policy: no-referrer-when-downgrade
    Feature-Policy: sync-xhr 'none'; camera 'none'; microphone 'none';
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    